services: 
  node-users-api:
    image: bitnami/postgresql:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRESQL_USERNAME=docker-postgres
      - POSTGRESQL_PASSWORD=JulioN4G4ita
      - POSTGRESQL_DATABASE=docker-postgres-db

